services:
    rebuttal-server:
        image: triggerhapp/rebuttal:main # Use latest git
        volumes:
            - './data:/data' # Both JSON and SQLite storage need a storage directory
            - './key.pem:/key.pem'
            - './cert.pen:/cert.pem' # Assuming you have a valid domain key & cert
        ports:
            - '443:9000'
