/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const AccountStorage = t.iface([], {
  "id": "UserUUID",
  "name": "string",
  "passwordHash": "string",
  "avatar": t.opt("string"),
  "email": "string",
  "group": "string",
  "hidden": t.opt("boolean"),
});

export const RoomStorage = t.iface([], {
  "id": "RoomUUID",
  "name": "string",
  "type": "string",
});

export const PermissionsStorage = t.iface([], {
  [t.indexKey]: t.array("string"),
});

export const pluginData = t.iface([], {
  [t.indexKey]: "string",
});

export const string_list = t.array("string");

export const bool = t.name("boolean");

export const idx = t.name("number");

export const str = t.name("string");

const exportedTypeSuite: t.ITypeSuite = {
  AccountStorage,
  RoomStorage,
  PermissionsStorage,
  pluginData,
  string_list,
  bool,
  idx,
  str,
};
export default exportedTypeSuite;
