name: Test Package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
# TODO, MySQL testing
#    env:
#      DB_DATABASE: rebuttal
#      DB_USER: root
#      DB_PASSWORD: root
#      DB_HOST: localhost
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 22
#      - run: sudo /etc/init.d/mysql start
      - run: openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"
      - run: yarn
      - run: yarn test
