name: Test Package

on: [push]
permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            DB_USER: test
            DB_PASSWORD: test
            DB_HOST: localhost
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: 'true'

            - uses: actions/checkout@v3
              with:
                  repository: 'RebuttalChat/RebuttalWebapp'
                  path: 'webapp'
                  submodules: 'true'

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 25

            - name: Start MySQL
              run: sudo mysql --user=test --password=test &

            - name: Create testing certificate
              run: openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"

            - name: Yarn Install Webapp
              uses: borales/actions-yarn@v4
              with:
                  cmd: install
                  dir: 'webapp'

            - name: Yarn Build Webapp
              uses: borales/actions-yarn@v4
              with:
                  cmd: build
                  dir: 'webapp'

            - name: Yarn install
              uses: borales/actions-yarn@v4
              with:
                  cmd: install

            - name: Yarn test
              uses: borales/actions-yarn@v4
              with:
                  cmd: test
