name: Test Package

on: [push]
permissions:
    contents: read

permissions:
  contents: read
  
jobs:
    test:
        runs-on: ubuntu-latest
        # TODO, MySQL testing
        #    env:
        #      DB_DATABASE: rebuttal
        #      DB_USER: root
        #      DB_PASSWORD: root
        #      DB_HOST: localhost
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            #      - name: Start MySQL
            #        run: sudo /etc/init.d/mysql start
            - name: Create testing certificate
              run: openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"

            - name: Yarn install
              uses: borales/actions-yarn@v4
              with:
                  cmd: install

            - name: Yarn test
              uses: borales/actions-yarn@v4
              with:
                  cmd: test
